backend:
  name: github
  repo: nolabelventures/nolabelventures.github.io # Path to your GitHub repository
  branch: main # Branch to update (optional; defaults to master)
  base_url: https://us-central1-nolabelventures.cloudfunctions.net
  auth_endpoint: /oauth/auth

media_folder: "assets/uploads"
collections:
  - name: about
    label: About Section
    identifier_field: content
    extension: yml
    folder: _data
    fields:
      - label: Content
        name: content
        widget: markdown
        required: true

  - name: "portfolio_items"
    label: "Portfolio Items"
    label_singular: "Portfolio Item"
    create: true
    extension: yml
    folder: '_data/portfolio'
    identifier_field: title
    sortable_fields: ['title']
    editor:
      preview: false
    widget: 'list'
    fields:
      - { label: 'Title', name: 'title', widget: 'text', required: true }
      - { label: 'URL', name: 'url', widget: 'text', required: true }
      - { label: 'Logo', name: 'image', widget: 'image', required: true }
  
  - name: faqs
    label: FAQs
    extension: yml
    folder: _data
    editor:
      preview: false
    fields:
      - label: FAQ
        name: faq
        widget: list
        required: true
        fields:
          - { label: 'Question', name: 'question', widget: 'text', required: true }
          - { label: 'Answer', name: 'answer', widget: 'text', required: true }

  - name: 'blog'
    label: 'Blog'
    folder: '_posts/'
    create: true
    slug: '{{year}}-{{month}}-{{day}}-{{slug}}'
    identifier_field: title
    editor:
      preview: false
    fields:
      - { label: 'Layout', name: 'layout', widget: 'hidden', default: 'post' }
      - { label: 'Title', name: 'title', widget: 'string', required: true }
      - { label: 'Publish Date', name: 'date', widget: 'datetime', required: true }
      - { label: 'Featured Image', name: 'thumbnail', widget: 'image', choose_url: false, required: true }
      - { label: 'Body', name: 'body', widget: 'markdown', required: true }
      - label: 'Related Articles'
        name: 'related'
        widget: 'list'
        max: 3
        label_singular: 'Article'
        fields:
          - { label: 'Title', name: 'title', widget: 'string' }
          - { label: 'Content', name: 'content', widget: 'text' }
          - { label: 'Image', name: 'thumbnail', widget: 'image', choose_url: false, allow_multiple: false }
          - { label: 'Related Article Link', name: 'link', widget: 'relation', collection: "blog", search_fields: ["title"], display_fields: ["title"], value_field: "{{slug}}", multpile: true }
